### ISSUE TITLE
More errors

### ISSUE THREAD

**Issue by herobrine30396** [NXPHoverGames/RapidIoT#3]
I still have 6 errors:

![error](https://user-images.githubusercontent.com/51438133/69953063-7edf7f80-151e-11ea-9de5-6eeb59cef499.png)

**Comment by herobrine30396** [comment]
@KatrinMoritz I followed the instructions but I got another error which was not mentioned in the gitbook

**Comment by KatrinMoritz** [comment]
@Niel66, can you please describe your problem more detailed? Which MCUXpresso version do you have? What have you done before you got the errors? Can you please describe your approach?

**Comment by herobrine30396** [comment]
Sorry for the late reply. I am using MCUXpresso v11.0.1. I followed the instructions before getting the error, I didn't do anything outside the instructions.

**Comment by herobrine30396** [comment]
I installed mcuxpresso v10.2 and it worked !
